---
title: "Proposal of P8105 Final Project"
date: "2023-11-07"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Participants
* Lu Qiu (lq2234)
* Zhiyi Zhu (zz3167)
* Chen Liang (cl4469)
* Ziqiu Liu (zl3386)
* Ruoxi Li (rl3401)

### Tentative Project title

Students Mental Health: Exploring Factors Associated with Students' Mental Well-being

### Motivation 



### Intended final products

* A website with homepage for overview of our project, a page for exploratory analyses, a page for statistical analyses, a page for interactive dashboard by R-Shiny, and a page for project report.
* A detailed project report.
* A two-minute narrated screencast illustrating our project.

### Data sources

* We plan to use the Kaggle open data set [Students Mental Health Assessments](https://www.kaggle.com/datasets/sonia22222/students-mental-health-assessments/data) which provides results of an anonymous survey with over 7000 college students' reponses. 

* It records each student's basic info (age, gender, department), CGPA, mental health related scores (`Stress_Level`, `Depression_Score`, `Depression_Score`), and other factors that may be associated with their mental health (e.g. sleep quality, physical activity, family history of mental health issues).

### Planned Analyses / visualizations / coding challenges

**Challenges:**

* Addressing Missing Data:
Within our extensive dataset, a substantial number of variables exhibit missing values.
* Enhancing Variable Selection:
As we strive to comprehensively examine aspects of stress level, depression score, anxiety score, and beyond, it is essential to broaden the spectrum of variables in our dataset.
* Data Quality Issues:
We need to ensure the quality of the data is crucial. Data may contain errors, outliers, or inconsistencies that can lead to biased or inaccurate results. 
* Website Design:
We plan to create a state-of-the-art website with advanced features and a visually appealing design.
* R-Shiny Interactive Dashboard: 
We plan to use R-Shiny to build an interactive platform.

### Planned timeline

* 11.11 Proposal
* 11.13~11.17 Project review meeting
* 11.18~11.21 Finish exploratory analyses
* 11.22~11.25 Finish statistical analyses
* 11.26~11.30 Finish the Shiny dashboard and begin to write the report
* 12.1~12.9 Finish the report and screencast



